import {CatalogQuery,freeCatalog} from './music-catalog';
// Apple documents JSONP specifically for cross-site searches. Deezer provides the
// same public transport. Only these two fixed HTTPS origins can execute callbacks.
export function jsonpCatalog(url:string):Promise<any>{const u=new URL(url);if(!['itunes.apple.com','api.deezer.com'].includes(u.hostname)||u.protocol!=='https:')return Promise.reject(new Error('Источник не поддерживает этот способ поиска.'));return new Promise((resolve,reject)=>{const name='tapeCatalog_'+crypto.randomUUID().replaceAll('-',''),script=document.createElement('script');let done=false;const clean=()=>{script.remove();clearTimeout(timer);delete (window as any)[name];};const finish=(data:any)=>{if(done)return;done=true;clean();resolve(data);};(window as any)[name]=finish;u.searchParams.set('callback',name);if(u.hostname==='api.deezer.com')u.searchParams.set('output','jsonp');const timer=setTimeout(()=>{if(done)return;done=true;clean();reject(new Error('Каталог не ответил за 15 секунд.'));},15000);script.src=u.href;script.onerror=()=>{if(done)return;done=true;clean();reject(new Error('Не удалось подключиться к каталогу.'));};document.head.appendChild(script);});}
async function browserJson(url:string){const u=new URL(url);if(u.hostname==='musicbrainz.org'){const r=await fetch(url,{signal:AbortSignal.timeout(12000),headers:{Accept:'application/json'}});if(!r.ok)throw new Error('MusicBrainz временно недоступен.');return r.json();}return jsonpCatalog(url);}
export async function searchCatalog(params:CatalogQuery){return freeCatalog(params,browserJson);}
async function fetchCatalogImage(url:string):Promise<string>{let blob:Blob|undefined;if(!blob){const u=new URL(url);if(!['image.tmdb.org','cdn-images.dzcdn.net','e-cdns-images.dzcdn.net'].includes(u.hostname)&&!/^is\d+-ssl\.mzstatic\.com$/.test(u.hostname))throw new Error('Обложка недоступна.');const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('Обложка недоступна.');blob=await r.blob();}if(!blob.type.startsWith('image/')||blob.size>15000000)throw new Error('Обложка недоступна.');return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob!);});}

export async function catalogImage(url:string):Promise<string>{const candidates=[url,url.replace(/\/\d+x\d+(bb)?([-.])/,'/500x500$1$2')];let failure:unknown;for(const candidate of [...new Set(candidates)]){try{return await fetchCatalogImage(candidate);}catch(e){failure=e;}}throw failure||new Error('Обложка недоступна.');}
