import {type Project,type FlapArtwork,albumKey,geometry} from './model';
import {flapTracklist} from './jcard';
import {fileData,loadImage} from './render';
const plain=(v:unknown)=>String(v||'').replace(/<[^>]*>/g,' ').replace(/&[a-z#0-9]+;/gi,' ').replace(/\s+/g,' ').trim().slice(0,500);
const clean=(v:string)=>v.replace(/["\\|:<>]/g,' ').replace(/\s+/g,' ').trim().slice(0,140);
export function imageQueries(p:Project){const title=clean(p.title),artist=clean(p.artist),text=(title+' '+artist).toLowerCase();const topic=/minecraft|майнкрафт|c418/.test(text)?'Minecraft':/terraria/.test(text)?'Terraria':/undertale/.test(text)?'Undertale':'';return [...new Set([title&&artist?`"${title}" "${artist}"`:title||artist,topic||artist||title].filter(Boolean))].slice(0,2);}
export type Candidate={title:string;url:string;page:string;width:number;height:number;size:number;artist:string;license:string;licenseUrl:string;score:number};
export function imageCandidates(data:any,query:string,w:number,h:number):Candidate[]{const terms=clean(query).toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(t=>t.length>2),ratio=w/h;return Object.values(data.query?.pages||{}).flatMap((page:any)=>{const i=page.imageinfo?.[0],m=i?.extmetadata;if(!i||!m||!['image/jpeg','image/png','image/webp'].includes(i.mime)||!/^https:\/\/upload\.wikimedia\.org\//.test(i.url)||!/^https:\/\/commons\.wikimedia\.org\//.test(i.descriptionurl))return [];const aspect=i.width/i.height,metadata=plain(page.title+' '+m.ImageDescription?.value+' '+m.ObjectName?.value).toLowerCase();const matches=terms.filter(t=>metadata.includes(t)).length,license=plain(m.LicenseShortName?.value);if(!matches||!license||i.width<Math.ceil(w/25.4*300)||i.height<400||i.size>8000000||aspect<ratio||aspect>.8||m.Restrictions?.value)return [];return [{title:plain(page.title).replace(/^File:/,''),url:i.url,page:i.descriptionurl,width:i.width,height:i.height,size:i.size,artist:plain(m.Artist?.value),license,licenseUrl:plain(m.LicenseUrl?.value),score:matches/Math.max(1,terms.length)*5-Math.abs(Math.log(aspect/ratio))}];}).sort((a,b)=>b.score-a.score);}
// The image is embedded unchanged. Layout dimensions follow its original aspect ratio.
export async function findFlapImage(p:Project):Promise<{artwork?:FlapArtwork;notice:string}>{const g=geometry(p),back=g.panels.find(x=>x.id==='back');if(!back||flapTracklist(p,g).fits)return {notice:''};const w=back.w-6,h=back.h-23,key=albumKey(p);if(p.flapArtwork?.albumKey===key)return {artwork:p.flapArtwork,notice:'Для клапана использовано найденное изображение альбома.'};const signal=AbortSignal.timeout(25000);let failed=false,seen=new Set<string>();for(const query of imageQueries(p)){try{const params=new URLSearchParams({action:'query',generator:'search',gsrsearch:query,gsrnamespace:'6',gsrlimit:'20',prop:'imageinfo',iiprop:'url|size|mime|extmetadata',iiextmetadatafilter:'Artist|LicenseShortName|LicenseUrl|ImageDescription|ObjectName|Restrictions',format:'json',origin:'*'});const r=await fetch('https://commons.wikimedia.org/w/api.php?'+params,{signal,credentials:'omit'});if(!r.ok)throw Error();const data=await r.json();if(data.error)throw Error();const candidates=imageCandidates(data,query,w,h).filter(c=>!seen.has(c.url));for(const c of candidates.slice(0,3)){seen.add(c.url);try{const response=await fetch(c.url,{signal,credentials:'omit'});if(!response.ok)continue;const blob=await response.blob();if(blob.size>8000000||!/^image\/(jpeg|png|webp)$/.test(blob.type))continue;const src=await fileData(blob),img=await loadImage(src);if(img.width!==c.width||img.height!==c.height)continue;const imageH=w*img.height/img.width;if(imageH>h)continue;return {artwork:{src,albumKey:key,title:c.title,page:c.page,artist:c.artist,license:c.license,licenseUrl:c.licenseUrl,w,h:imageH},notice:'Изображение для клапана найдено в Wikimedia Commons. Пропорции сохранены, обрезки нет.'};}catch{failed=true;}}}catch{failed=true;if(signal.aborted)break;}}
return {notice:failed?'Поиск изображения недоступен или файлы не загрузились. Клапан оставлен без изображения.':'Подходящего по теме, пропорциям и разрешению изображения не найдено. Клапан оставлен без изображения.'};}
