export type AudioCandidate={source:'commons'|'archive';id:string;file:string;title:string;artist:string;url:string;page:string;license:string;licenseUrl:string;size:number};
export type AudioRequest={title:string;artist?:string;album?:string};
export type GetJson=(url:string)=>Promise<any>;
const plain=(s:any)=>String(Array.isArray(s)?s.join(', '):s||'').replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"');
export const normalizeAudio=(s:string)=>s.toLowerCase().normalize('NFKD').replace(/\.[a-z0-9]{2,5}$/i,'').replace(/^\d+[ ._-]+/,'').replace(/[^\p{L}\p{N}]/gu,'');
export function downloadableLicense(raw:string){try{const u=new URL(raw);if(!['creativecommons.org','www.creativecommons.org'].includes(u.hostname)||!['http:','https:'].includes(u.protocol))return false;return /^\/(licenses\/(by|by-sa|by-nc|by-nc-sa|by-nd|by-nc-nd)\/\d\.\d|publicdomain\/(zero|mark)\/1\.0)\//.test(u.pathname);}catch{return false;}}
export function exactAudio(c:AudioCandidate,t:AudioRequest){const title=normalizeAudio(t.title),artist=normalizeAudio(t.artist||'');return !!title&&(normalizeAudio(c.title)===title||!!artist&&normalizeAudio(c.title)===artist+title)&&(!artist||normalizeAudio(c.artist).includes(artist));}
export function commonsCandidates(d:any):AudioCandidate[]{return Object.values(d.query?.pages||{}).flatMap((p:any)=>{const i=p.imageinfo?.[0],m=i?.extmetadata;if(!i||!m||!(/^(audio\/|application\/ogg)/.test(i.mime||'')))return [];const licenseUrl=m.LicenseUrl?.value||'';if(!downloadableLicense(licenseUrl))return [];return [{source:'commons',id:p.title,file:p.title.replace(/^File:/,''),title:plain(m.ObjectName?.value||p.title.replace(/^File:/,'')),artist:plain(m.Artist?.value||m.Credit?.value),url:i.url,page:i.descriptionurl,license:plain(m.LicenseShortName?.value)||'Creative Commons',licenseUrl,size:Number(i.size)||0}];});}
export function archiveCandidates(id:string,d:any):AudioCandidate[]{const m=d.metadata||{},licenseUrl=plain(m.licenseurl);if(d.is_dark||m.access_restricted==='true'||!downloadableLicense(licenseUrl))return [];return (d.files||[]).filter((f:any)=>!f.private&&!f.restricted&&/\.(mp3|ogg|flac|wav|m4a|opus)$/i.test(f.name||'')&&!/(sample|preview)/i.test(f.name||'')).map((f:any)=>({source:'archive',id,file:f.name,title:plain(f.title||f.name.split('/').pop().replace(/\.[^.]+$/,'').replace(/^\d+[ ._-]+/,'')),artist:plain(f.creator||m.creator),url:`https://archive.org/download/${encodeURIComponent(id)}/${f.name.split('/').map(encodeURIComponent).join('/')}`,page:`https://archive.org/details/${encodeURIComponent(id)}`,license:licenseUrl.includes('/publicdomain/')?'Public domain / CC0':licenseUrl.match(/\/licenses\/([^/]+)/)?.[1].toUpperCase()||'CC',licenseUrl,size:Number(f.size)||0}));}
export async function searchFreeAudio(t:AudioRequest,get:GetJson){const clean=(x:string)=>x.replace(/["\\]/g,' ').slice(0,160),title=clean(t.title),artist=clean(t.artist||''),album=clean(t.album||'');const problems:string[]=[];const results:AudioCandidate[]=[];
 await Promise.allSettled([(async()=>{try{const u=new URL('https://commons.wikimedia.org/w/api.php');for(const [k,v] of Object.entries({action:'query',generator:'search',gsrsearch:`${title} ${artist} filetype:audio`,gsrnamespace:'6',gsrlimit:'8',prop:'imageinfo',iiprop:'url|size|mime|extmetadata',format:'json',origin:'*'}))u.searchParams.set(k,v);const d=await get(u.href);if(d.error)throw new Error(d.error.info||'Ошибка источника');results.push(...commonsCandidates(d));}catch{problems.push('Wikimedia Commons сейчас недоступен');}})(),(async()=>{try{const seen=new Set<string>();const relevant=(c:AudioCandidate)=>normalizeAudio(c.title).includes(normalizeAudio(title))||normalizeAudio(title).includes(normalizeAudio(c.title));const queries=[`mediatype:audio AND licenseurl:* AND (title:"${title}"${album?` OR title:"${album}"`:''})${artist?` AND creator:"${artist}"`:''}`];if(artist)queries.push(`mediatype:audio AND licenseurl:* AND creator:"${artist}"`);for(const query of queries){const u=new URL('https://archive.org/advancedsearch.php');u.searchParams.set('q',query);u.searchParams.set('output','json');u.searchParams.set('rows',artist?'8':'4');u.searchParams.append('fl[]','identifier');const d=await get(u.href);if(!d.response)throw new Error('Ошибка источника');const docs=(d.response.docs||[]).filter((x:any)=>/^[a-zA-Z0-9_.-]+$/.test(x.identifier)&&!seen.has(x.identifier));for(let i=0;i<docs.length;i+=2){await Promise.all(docs.slice(i,i+2).map(async(doc:any)=>{seen.add(doc.identifier);try{const item=await get(`https://archive.org/metadata/${doc.identifier}`);results.push(...archiveCandidates(doc.identifier,item).filter(relevant));}catch{problems.push('Не удалось прочитать одно из изданий Internet Archive');}}));}if(results.some(c=>c.source==='archive'&&exactAudio(c,t)))break;}}catch{problems.push('Internet Archive сейчас недоступен');}})()]);
 const dedup=new Map<string,AudioCandidate>();for(const c of results){const key=c.source+'|'+c.id+'|'+normalizeAudio(c.title);const old=dedup.get(key);if(!old||/\.mp3$/i.test(c.file))dedup.set(key,c);}return {results:[...dedup.values()].sort((a,b)=>Number(exactAudio(b,t))-Number(exactAudio(a,t))).slice(0,16),problems};}
