import {type Project,completeJcard,albumArtwork,geometry} from './model';
import {loadImage,fileData,loadFonts} from './render';
export const styles=['editorial','pixel','electronic','classical','minimal'] as const;
export type DesignStyle=typeof styles[number];
export type DesignPlan={style:DesignStyle;paper:string;ink:string;accent:string;reason:string};
const luminance=(hex:string)=>{const c=hex.match(/\w\w/g)!.map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return c[0]*.2126+c[1]*.7152+c[2]*.0722;};
const contrasting=(paper:string)=>luminance(paper)>.36?'#18221e':'#faf8ef';
export async function localPlan(p:Project,choice:string):Promise<DesignPlan>{const s=(p.title+' '+p.artist+' '+p.description).toLowerCase();const style=styles.includes(choice as DesignStyle)?choice as DesignStyle:/minecraft|c418|майнкрафт|terraria|undertale|8.bit|chiptune/.test(s)?'pixel':/daft punk|electro|synth|cyber|электрон/.test(s)?'electronic':/classic|orchestra|symphon|классик|оркестр/.test(s)?'classical':'editorial';let paper=style==='pixel'?'#273d35':style==='electronic'?'#18232d':style==='classical'?'#ece3d3':'#e9e7df',accent=style==='pixel'?'#99cf71':style==='electronic'?'#6fc9ce':'#a77e53';const art=albumArtwork(p);if(art?.src){try{const image=await loadImage(art.src),c=document.createElement('canvas');c.width=c.height=24;const x=c.getContext('2d')!;x.drawImage(image,0,0,24,24);const d=x.getImageData(0,0,24,24).data;let r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=4){if(d[i+3]<128)continue;r+=d[i];g+=d[i+1];b+=d[i+2];n++;}if(n){const hex=(a:number[])=>'#'+a.map(v=>Math.round(v).toString(16).padStart(2,'0')).join('');paper=hex([r/n,g/n,b/n].map(v=>style==='classical'?v*.2+235*.8:v*.28+18*.72));accent=hex([r/n,g/n,b/n].map(v=>v*.55+190*.45));}}catch{}}
 return {style,paper,ink:contrasting(paper),accent,reason:style==='pixel'?'Пиксельная типографика и блочная графика, вдохновлённые игровым альбомом.':'Палитра обложки, единая типографика и отдельный фон для каждой части комплекта.'};}
export function validatePlan(raw:any):DesignPlan{if(!raw||!styles.includes(raw.style)||!['paper','ink','accent'].every(k=>/^#[\da-f]{6}$/i.test(raw[k]))||typeof raw.reason!=='string')throw new Error('Неподходящие настройки оформления.');return {style:raw.style,paper:raw.paper,ink:contrasting(raw.paper),accent:raw.accent,reason:raw.reason.slice(0,240)};}
export async function applyDesign(p:Project,plan:DesignPlan){let next=completeJcard(p);const g=geometry(next),front=g.panels.find(x=>x.id==='front')!,art=albumArtwork(next);const titleFont=plan.style==='pixel'?'Press Start 2P':plan.style==='classical'?'Georgia':plan.style==='electronic'?'Trebuchet MS':'Arial';if(plan.style==='pixel'&&!next.fonts.some(f=>f.name===titleFont)){const r=await fetch('./fonts/PressStart2P.ttf');if(!r.ok)throw new Error('Пиксельный шрифт не загрузился');next={...next,fonts:[...next.fonts,{name:titleFont,src:await fileData(await r.blob())}]};}
 const square=front.w-12;next={...next,smartDesign:{...plan},paper:plan.paper,ink:plan.ink,accent:plan.accent,titleFont,bodyFont:titleFont,spineFont:titleFont,titleSize:plan.style==='pixel'?12:20,bodySize:7.5,trackSize:7.5,overlay:'none',titlePos:'top',panelColors:{},booklet:{...next.booklet!,panorama:undefined,innerPaper:plan.paper,innerInk:plan.ink},layers:next.layers.map(l=>l.id===art?.id?{...l,x:front.x+6,y:24,w:square,h:square,fit:'contain' as const,cropX:0,cropY:0,zoom:1}:l),builtin:{...next.builtin,title:{y:5,h:12,align:'center',vAlign:'middle'},artist:{y:18,h:5,align:'center'},'inner-cover-art':{x:0,y:24,w:square,h:square,fit:'contain'},'inner-cover-title':{y:5,h:12,align:'center'},'inner-cover-credit':{y:front.h-13,h:9,size:6.5}}};delete next.builtin['inner-cover-art'];await loadFonts(next);return next;}
