import {fullJcardLayers,labelLayers} from './jcard';
export type Layer = {id:string;name:string;type:'text'|'image'|'rect'|'ellipse';x:number;y:number;w:number;h:number;rotation:number;opacity:number;visible:boolean;locked:boolean;text?:string;src?:string;color:string;bg?:string;font:string;size:number;bold?:boolean;italic?:boolean;align:'left'|'center'|'right';fit?:'cover'|'contain'|'stretch';cropX?:number;cropY?:number;zoom?:number;radius?:number;border?:number;borderColor?:string;blend?:GlobalCompositeOperation;blur?:number;invert?:boolean;grayscale?:boolean;tint?:string;flipX?:boolean;flipY?:boolean;tile?:boolean;panel?:string;auto?:boolean;side?:SheetSide;wrap?:boolean;vAlign?:'top'|'middle'|'bottom';minSize?:number;blockAlign?:'center';badgeIcon?:'hifi'|'stereo'|'music'|'dolby'};
export type SheetSide='outer'|'inner'|'labelA'|'labelB';
export type Booklet={enabled:boolean;panels:number;autoPages:boolean;labels:boolean;badges:string[];label:string;innerPaper:string;innerInk:string;panorama?:string;notes:string};
export type Track={id:string;title:string;duration:string;artist?:string;description?:string};
export type Format={id:string;name:string;group:string;kind:'jcard'|'box'|'wrap'|'label'|'disc'|'tray'|'square'|'cassingle'|'obi';w:number;h:number;d:number;flap?:number;hole?:number;verified?:boolean;desc:string};
const allFormats:Format[]=[
{id:'jcard',name:'J-card · стандарт',group:'Кассеты',kind:'jcard',w:65.0875,h:101.6,d:12.7,flap:25.4,verified:true,desc:'Короткий клапан 25,4 мм · Norelco'},
{id:'jcard-tall',name:'J-card · высокий клапан',group:'Кассеты',kind:'jcard',w:65.0875,h:101.6,d:12.7,flap:50.8,verified:true,desc:'Высокий клапан 50,8 мм · Norelco'},
{id:'cassingle',name:'Cassingle · O-card',group:'Кассеты',kind:'cassingle',w:63.5,h:103.251,d:12.7,flap:12.7,verified:true,desc:'Конверт для корпуса · 165,1 × 103,251 мм'},
{id:'cassette',name:'Кассета · этикетка',group:'Кассеты',kind:'label',w:89,h:41,d:0,verified:true,desc:'Этикетка 89 × 41 мм · Cassette Express'},
{id:'slipcover',name:'VHS · коробка',group:'VHS',kind:'box',w:104.394,h:187.96,d:25.6032,verified:true,desc:'Коробка с клеевым клапаном'},
{id:'side-load-vhs',name:'VHS · боковая загрузка',group:'VHS',kind:'box',w:187.96,h:104.394,d:25.6032,desc:'Горизонтальная коробка'},
{id:'compact-tape',name:'VHS · компактная коробка',group:'VHS',kind:'box',w:103,h:185,d:25,desc:'Плотная посадка под кассету'},
{id:'doublevhs',name:'VHS · двойная коробка',group:'VHS',kind:'box',w:104.394,h:187.96,d:51.2064,desc:'Для двух видеокассет'},
{id:'polycase',name:'VHS · Polycase',group:'VHS',kind:'wrap',w:110,h:200,d:30,desc:'Вкладыш пластикового футляра'},
{id:'clamshell',name:'VHS · Clamshell',group:'VHS',kind:'wrap',w:119,h:203,d:32,desc:'Вкладыш большого футляра'},
{id:'vhslabels',name:'VHS · наклейки',group:'VHS',kind:'label',w:145,h:80,d:0,desc:'Лицевая этикетка + корешок'},
{id:'blockbuster',name:'VHS · прокатный конверт',group:'VHS',kind:'box',w:104.4,h:188,d:25.6,desc:'Сине-жёлтая прокатная тема'},
{id:'movie-gallery',name:'VHS · Movie Gallery',group:'VHS',kind:'box',w:104.4,h:188,d:25.6,desc:'Красная прокатная тема'},
{id:'hollywood-video',name:'VHS · Hollywood Video',group:'VHS',kind:'box',w:104.4,h:188,d:25.6,desc:'Фиолетовая прокатная тема'},
{id:'video-ezy',name:'VHS · Video Ezy',group:'VHS',kind:'box',w:104.4,h:188,d:25.6,desc:'Оранжевая прокатная тема'},
{id:'betamax',name:'Betamax · коробка',group:'Betamax',kind:'box',w:96,h:157,d:25.4,desc:'Коробка для Betamax'},
{id:'betamax-labels',name:'Betamax · этикетки',group:'Betamax',kind:'label',w:120,h:55,d:0,desc:'Лицевая этикетка и корешок'},
{id:'dvd-cover',name:'DVD · обложка',group:'Диски',kind:'wrap',w:129,h:183,d:14,desc:'Вкладыш стандартного DVD-футляра'},
{id:'bluray-cover',name:'Blu-ray · обложка',group:'Диски',kind:'wrap',w:129,h:149,d:12,desc:'Вкладыш Blu-ray-футляра'},
{id:'bluray-slipcover',name:'Blu-ray · O-card',group:'Диски',kind:'box',w:135,h:171,d:15,desc:'Внешний картонный чехол'},
{id:'steelcase',name:'SteelBook · обложка',group:'Диски',kind:'wrap',w:136,h:171,d:15,desc:'Развёртка для металлического футляра'},
{id:'disc',name:'Диск · этикетка',group:'Диски',kind:'disc',w:120,h:120,d:0,hole:22,desc:'Круглая этикетка CD / DVD'},
{id:'cd',name:'CD · этикетка',group:'CD',kind:'disc',w:118,h:118,d:0,hole:41,desc:'Этикетка с большим отверстием'},
{id:'cd-insert',name:'CD · вкладыш',group:'CD',kind:'square',w:120,h:120,d:0,desc:'Передняя обложка Jewel Case'},
{id:'cd-tray',name:'CD · задник',group:'CD',kind:'tray',w:138,h:118,d:6,desc:'Задняя вставка с двумя корешками'},
{id:'vinyl-label',name:'Винил · этикетка',group:'Винил',kind:'disc',w:100,h:100,d:0,hole:7.2,desc:'Центральная этикетка пластинки'},
{id:'vinyl-jacket',name:'Винил · обложка',group:'Винил',kind:'box',w:315,h:315,d:4,desc:'Конверт 12-дюймовой пластинки'},
{id:'vinyl-sleeve',name:'Винил · внутренний конверт',group:'Винил',kind:'square',w:307,h:307,d:0,desc:'Внутренняя вставка 12″'},
{id:'obi-strip',name:'Obi · лента',group:'Винил',kind:'obi',w:50,h:315,d:4,desc:'Поясная лента для обложки'},
{id:'minidisc-label',name:'MiniDisc · этикетка',group:'MiniDisc',kind:'label',w:54,h:37,d:0,desc:'Наклейка на MiniDisc'},
{id:'minidisc-full-labels',name:'MiniDisc · полная этикетка',group:'MiniDisc',kind:'label',w:68,h:64,d:0,desc:'Наклейка на всю лицевую сторону'},
{id:'minidisc-jcard',name:'MiniDisc · J-card',group:'MiniDisc',kind:'jcard',w:68,h:72,d:6,flap:24,desc:'Вкладыш с корешком и клапаном'},
{id:'minidisc-cover',name:'MiniDisc · обложка',group:'MiniDisc',kind:'square',w:72,h:72,d:0,desc:'Передняя обложка футляра'},
{id:'minidisc-tray',name:'MiniDisc · задник',group:'MiniDisc',kind:'tray',w:70,h:72,d:6,desc:'Задняя вставка футляра'},
{id:'cardbox',name:'Карты · коробка',group:'Другое',kind:'box',w:64,h:89,d:20,desc:'Коробка для колоды карт'},
{id:'custom',name:'Свой размер',group:'Другое',kind:'square',w:100,h:150,d:0,desc:'Произвольный прямоугольный макет'}
];
export const formats=allFormats.filter(f=>f.group==='Кассеты'&&f.id!=='jcard-tall');
export const INSERT_WIDTH=63.5;
export const LABEL_WIDTH=89, LABEL_HEIGHT=41;
export type Panel={id:string;name:string;x:number;y:number;w:number;h:number};
export type Geometry={w:number;h:number;panels:Panel[];folds:{x1:number;y1:number;x2:number;y2:number}[];outline:number[][];hole?:number;disc?:boolean;cutouts?:{x:number;y:number;w:number;h:number;r:number}[]};
export type Project={smartDesign?:{style:string;paper:string;ink:string;accent:string;reason:string};booklet?:Booklet;version:1;name:string;format:string;dimensions:{w:number;h:number;d:number;flap:number;hole:number};insert:boolean;fullFlap:boolean;notch:boolean;paper:string;ink:string;accent:string;theme:string;title:string;artist:string;year:string;catalog:string;tagline:string;description:string;runtime:string;rating:string;cast:string;credits:string;origin:string;budget:string;revenue:string;warning:string;titlePos:string;titleFont:string;bodyFont:string;spineFont:string;titleSize:number;bodySize:number;spineSize:number;trackSize:number;creditsStyle:string;hideMeta:boolean;hideRules:boolean;hideText:boolean;hideSpine:boolean;showTrackNumbers:boolean;overlay:string;overlayColor:string;overlayOpacity:number;wear:number;folds:boolean;cuts:boolean;grid:boolean;bleed:number;layers:Layer[];tracksA:Track[];tracksB:Track[];fonts:{name:string;src:string}[];builtin:Record<string,Partial<Layer>>;panelColors:Record<string,string>;backLayout:string;lockDesign:boolean;sourceLink?:string;sourceName?:string};
export function geometry(p:Project):Geometry{const f=formats.find(x=>x.id===p.format)||formats[0],{w,h,d,flap,hole}=p.dimensions;let panels:Panel[]=[],tw=w,th=h,outline:number[][]=[],cutouts:Geometry['cutouts'];const add=(id:string,name:string,x:number,y:number,pw:number,ph:number)=>panels.push({id,name,x,y,w:pw,h:ph});
 if(f.kind==='jcard'){add('back','Клапан',0,0,flap,h);add('spine','Корешок',flap,0,d,h);add('front','Обложка',flap+d,0,w,h);tw=flap+d+w;if(p.insert){const n=p.booklet?.enabled?bookletPanelCount(p):1;for(let i=0;i<n;i++){add(i?'insert'+(i+1):'insert','Вкладыш '+(i+1),tw,0,INSERT_WIDTH,h);tw+=INSERT_WIDTH;}}}
 else if(f.kind==='cassingle'){add('glue','Клей',0,0,flap,h);add('back','Оборот',flap,0,w,h);add('spine','Корешок',flap+w,0,d,h);add('front','Обложка',flap+w+d,0,w,h);add('tuck','Клапан',flap+w*2+d,0,d,h);tw=flap+w*2+d*2;}
 else if(f.kind==='box'){const glue=12.7,top=d*.9,bottom=d*.86+(p.fullFlap?d*.6:0);tw=glue+2*w+2*d;th=top+h+bottom;add('glue','Клей',0,top,glue,h);add('back','Оборот',glue,top,w,h);add('spine','Корешок',glue+w,top,d,h);add('front','Обложка',glue+w+d,top,w,h);add('spine2','Корешок 2',glue+2*w+d,top,d,h);add('top','Верх',glue+w+d,0,w,top);add('bottom','Низ',glue+w+d,top+h,w,bottom);
 outline=[[0,top+5],[glue,top],[glue,top*.25],[glue+5,0],[glue+w-5,0],[glue+w,top*.25],[glue+w,top],[glue+w+d,top],[glue+w+d,3],[glue+w+d+3,0],[glue+2*w+d-3,0],[glue+2*w+d,3],[glue+2*w+d,top],[tw,top],[tw,top+h],[glue+2*w+d,top+h],[glue+2*w+d,th-3],[glue+2*w+d-3,th],[glue+w+d+3,th],[glue+w+d,th-3],[glue+w+d,top+h],[glue+w,top+h],[glue+w,th-4],[glue+w-4,th],[glue+4,th],[glue,th-4],[glue,top+h],[0,top+h-5]];}
 else if(f.kind==='wrap'){add('back','Оборот',0,0,w,h);add('spine','Корешок',w,0,d,h);add('front','Обложка',w+d,0,w,h);tw=w*2+d;}
 else if(f.kind==='tray'){add('spine','Корешок',0,0,d,h);add('back','Оборот',d,0,w,h);add('spine2','Корешок 2',d+w,0,d,h);tw=w+2*d;}
 else if(f.kind==='obi'){add('back','Оборот',0,0,w,h);add('spine','Сгиб',0,h,w,d);add('front','Лицевая часть',0,h+d,w,h);th=h*2+d;}
 else {add('front','Обложка',0,0,w,h);if(p.format==='cassette')cutouts=[{x:w*.23,y:h*.37,w:w*.54,h:h*.36,r:3}];if(p.format==='vhslabels'||p.format==='betamax-labels'){panels=[];add('front','Лицевая этикетка',0,0,w,h*.7);add('spine','Корешок',0,h*.78,w,h*.22);cutouts=[{x:0,y:h*.7,w,h:h*.08,r:0}];}}
 const folds:Geometry['folds']=[];if(f.kind==='obi'){folds.push({x1:0,y1:h,x2:w,y2:h},{x1:0,y1:h+d,x2:w,y2:h+d});}else if(!['square','label','disc'].includes(f.kind)){panels.filter(x=>x.y===panels[0].y&&x.x>0).forEach(x=>folds.push({x1:x.x,y1:x.y,x2:x.x,y2:x.y+x.h}));if(f.kind==='box'){folds.push({x1:12.7,y1:panels[0].y,x2:tw,y2:panels[0].y},{x1:12.7,y1:panels[0].y+h,x2:tw,y2:panels[0].y+h});}}
 if(!outline.length)outline=[[0,0],[tw,0],[tw,th],[0,th]];return {w:tw,h:th,panels,folds,outline,disc:f.kind==='disc',hole,cutouts};}
export function defaultProject():Project{return {version:1,name:'Полночь · Vol. 01',format:'jcard',dimensions:{w:65.0875,h:101.6,d:12.7,flap:25.4,hole:7.2},insert:false,fullFlap:false,notch:false,paper:'#e9e7df',ink:'#17201e',accent:'#d5f76e',theme:'signal',title:'ПОЛНОЧЬ',artist:'ТИХИЕ ЧАСТОТЫ',year:'2026',catalog:'VOL. 01 / C60',tagline:'МУЗЫКА ПОСЛЕ ПОЛУНОЧИ',description:'Записи для долгой дороги, пустых улиц и тех часов, когда город становится тише.',runtime:'90',rating:'12+',cast:'',credits:'Составлено и записано с любовью.\nСтерео • Две стороны одной истории.',origin:'RU',budget:'',revenue:'',warning:'Личная коллекция. Все права на записи принадлежат их авторам.',titlePos:'bottom',titleFont:'Arial',bodyFont:'Arial',spineFont:'Arial',titleSize:24,bodySize:8,spineSize:10,trackSize:8,creditsStyle:'classic',hideMeta:false,hideRules:false,hideText:false,hideSpine:false,showTrackNumbers:false,overlay:'none',overlayColor:'#111111',overlayOpacity:65,wear:0,folds:true,cuts:true,grid:false,bleed:0,layers:[],tracksA:['Ночной поезд','Электрический сон','Свет в окне','Город без имён'].map((title,i)=>({id:'a'+i,title,duration:['3:41','4:02','2:58','5:11'][i]})),tracksB:['Низкая орбита','После дождя','Последний свет','До рассвета'].map((title,i)=>({id:'b'+i,title,duration:['3:27','4:44','3:09','6:20'][i]})),fonts:[],builtin:{},panelColors:{},backLayout:'row',lockDesign:false};}
export function layer(partial:Partial<Layer>):Layer{return {id:crypto.randomUUID(),name:'Текст',type:'text',x:10,y:10,w:45,h:15,rotation:0,opacity:1,visible:true,locked:false,color:'#17201e',font:'Arial',size:12,align:'left',fit:'cover',...partial};}
export const fonts=['Arial','Georgia','Times New Roman','Verdana','Trebuchet MS','Courier New','Impact','system-ui'];
export function builtinLayers(p:Project,side:SheetSide='outer'):Layer[]{if(side==='labelA'||side==='labelB')return labelLayers(p,side);if(p.booklet?.enabled&&formats.find(x=>x.id===p.format)?.kind==='jcard')return fullJcardLayers(p,sheetGeometry(p,side),side);if(side==='inner')return [];const g=geometry(p),f=formats.find(x=>x.id===p.format)!,out:Layer[]=[];const make=(id:string,part:Partial<Layer>)=>{const l={id,name:id,type:'text',x:0,y:0,w:10,h:10,rotation:0,opacity:1,visible:!p.hideText,locked:false,color:p.ink,font:p.bodyFont,size:p.bodySize,align:'left',auto:true,...part,...p.builtin[id]} as Layer;out.push(l);};
 const front=g.panels.find(x=>x.id==='front')||g.panels.find(x=>x.id==='back')!;const small=front.w<80;const margin=Math.min(6,front.w*.07);let ty=p.titlePos==='top'?front.y+margin+8:p.titlePos==='center'?front.y+front.h*.45:front.y+front.h*.66;
 if(p.titlePos!=='hidden'){make('title',{name:'Название',x:front.x+margin,y:ty,w:front.w-margin*2,h:front.h*.19,text:p.title,font:p.titleFont,size:p.titleSize,bold:true});make('artist',{name:'Исполнитель / автор',x:front.x+margin,y:ty-8,w:front.w-margin*2,h:7,text:p.artist,font:p.titleFont,size:Math.max(7,p.titleSize*.32),bold:true});make('catalog',{name:'Год и каталог',x:front.x+margin,y:front.y+front.h-10,w:front.w-margin*2,h:6,text:[p.year,p.catalog].filter(Boolean).join('  ·  '),size:7});}
 g.panels.filter(x=>x.id.startsWith('spine')).forEach(panel=>{const horizontal=panel.w>panel.h;const lw=horizontal?panel.w-8:panel.h-12,lh=horizontal?panel.h-2:panel.w-3;for(const [suffix,text,offset] of [['-artist',p.artist,-lh/4],['-title',p.title,lh/4]] as const)make(panel.id+suffix,{name:suffix==='-title'?'Название альбома · корешок':'Исполнитель · корешок',x:panel.x+panel.w/2-lw/2-(horizontal?0:offset),y:panel.y+panel.h/2-lh/4+(horizontal?offset:0),w:lw,h:lh/2,rotation:horizontal?0:90,text,font:p.spineFont,size:suffix==='-artist'?Math.min(8,p.spineSize):p.spineSize,bold:true,align:'center',vAlign:'middle',visible:!p.hideSpine&&!p.hideText});});
 const back=g.panels.find(x=>x.id==='back');const tracks=(t:Track[])=>t.map((x,i)=>`${p.showTrackNumbers?String(i+1).padStart(2,'0')+'. ':''}${x.title}${x.duration?'   '+x.duration:''}`).join('\n');
 if(back){if(f.kind==='jcard'){const bw=back.h-8,bh=back.w/2-3;['A','B'].forEach((side,i)=>make('tracks'+side,{name:'Треки · сторона '+side,x:back.x+back.w*(i?.75:.25)-bw/2,y:back.y+back.h/2-bh/2,w:bw,h:bh,rotation:90,text:`**СТОРОНА ${side}**\n`+tracks(i?p.tracksB:p.tracksA),size:p.trackSize}));}
 else {make('back-title',{name:'Заголовок оборота',x:back.x+6,y:back.y+7,w:back.w-12,h:15,text:p.tagline||p.title,font:p.titleFont,size:Math.min(p.titleSize*.58,20),bold:true});const music=['Кассеты','CD','Винил','MiniDisc'].includes(f.group);if(music){make('tracksA',{name:'Треки · сторона A',x:back.x+6,y:back.y+25,w:(back.w-18)/2,h:back.h*.55,text:'**СТОРОНА A**\n'+tracks(p.tracksA),size:p.trackSize});make('tracksB',{name:'Треки · сторона B',x:back.x+back.w/2+3,y:back.y+25,w:(back.w-18)/2,h:back.h*.55,text:'**СТОРОНА B**\n'+tracks(p.tracksB),size:p.trackSize});}else{make('overview',{name:'Описание',x:back.x+6,y:back.y+back.h*.32,w:back.w-12,h:back.h*.3,text:p.description,size:p.bodySize});make('cast',{name:'В ролях',x:back.x+6,y:back.y+back.h*.65,w:back.w-12,h:12,text:p.cast,size:p.bodySize,bold:true});}make('credits',{name:'Титры',x:back.x+6,y:back.y+back.h*.77,w:back.w-12,h:back.h*.11,text:p.credits,size:p.creditsStyle==='billing'?6:p.bodySize,font:p.creditsStyle==='billing'?'Impact':p.bodyFont});make('meta',{name:'Служебные данные',x:back.x+6,y:back.y+back.h*.9,w:back.w-12,h:7,text:[p.year,p.origin,p.runtime?p.runtime+' мин':'',p.rating,p.budget,p.revenue].filter(Boolean).join(' · '),size:6,visible:!p.hideMeta&&!p.hideText});make('warning',{name:'Примечание',x:back.x+6,y:back.y+back.h*.95,w:back.w-12,h:back.h*.04,text:p.warning,size:5});}}
 const insert=g.panels.find(x=>x.id==='insert');if(insert)make('insert-notes',{name:'Текст вкладыша',x:insert.x+6,y:insert.y+8,w:insert.w-12,h:insert.h-16,text:p.description+'\n\n'+p.credits,size:p.bodySize});
 return out;}
export function allLayers(p:Project,side:SheetSide='outer'){const custom=p.layers.filter(x=>(x.side||'outer')===side);const automatic=builtinLayers(p,side);return [...automatic.filter(x=>x.panel==='background'),...custom.filter(x=>x.panel==='background'),...automatic.filter(x=>x.panel!=='background'),...custom.filter(x=>x.panel!=='background')];}
export function applyFormat(p:Project,id:string):Project{const f=formats.find(x=>x.id===id)!;return {...p,format:id,dimensions:{w:f.w,h:f.h,d:f.d,flap:f.flap||25.4,hole:f.hole||7.2},builtin:{},panelColors:{},insert:false,booklet:p.booklet?{...p.booklet,enabled:false}:undefined,fullFlap:id==='cardbox',theme:['blockbuster','movie-gallery','hollywood-video','video-ezy'].includes(id)?id:p.theme};}
export function validateProject(value:any):Project{if(value?.format==='jcard-tall')value={...value,format:'jcard'};if(!value||value.version!==1||!formats.some(x=>x.id===value.format)||!Array.isArray(value.layers)||!value.dimensions)throw new Error('Это не проект Tape Studio версии 1.');for(const k of ['w','h','d','flap','hole'])if(!Number.isFinite(value.dimensions[k])||value.dimensions[k]<0||value.dimensions[k]>700)throw new Error('Недопустимые размеры макета');if(value.dimensions.w<10||value.dimensions.h<10)throw new Error('Макет слишком мал');if(value.layers.length>300)throw new Error('В проекте слишком много слоёв');const p={...defaultProject(),...value};if(p.sourceLink){try{const url=new URL(p.sourceLink);if(!['https:','http:'].includes(url.protocol))delete p.sourceLink;}catch{delete p.sourceLink;}}if(p.booklet){if(!Array.isArray(p.booklet.badges)||p.booklet.badges.some((x:any)=>typeof x!=='string')||!Number.isFinite(p.booklet.panels))throw new Error('Повреждены настройки вкладыша');p.booklet={...defaultBooklet(),...p.booklet,panels:Math.max(1,Math.min(4,Math.round(p.booklet.panels))),badges:p.booklet.badges.filter(Boolean).slice(0,p.booklet.label?.trim()?2:3)};if(p.booklet.panorama&&!/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(p.booklet.panorama))throw new Error('Панорама должна быть встроена');}for(const x of p.layers){if(!['text','image','rect','ellipse'].includes(x.type)||![x.x,x.y,x.w,x.h,x.rotation,x.opacity].every(Number.isFinite)||x.w<.1||x.h<.1||x.w>2000||x.h>2000)throw new Error('Повреждённый слой');if(x.src&&!/^data:image\/(png|jpeg|webp|gif|avif);base64,/.test(x.src))throw new Error('Изображения в проекте должны быть встроены');}for(const f of p.fonts)if(!/^data:/.test(f.src))throw new Error('Шрифт должен быть встроен');if(p.smartDesign&&!(['editorial','pixel','electronic','classical','minimal'].includes(p.smartDesign.style)&&[p.smartDesign.paper,p.smartDesign.ink,p.smartDesign.accent].every((v:any)=>/^#[0-9a-f]{6}$/i.test(v))))throw new Error('Повреждён стиль оформления');return fitJcardLayout(p);}

export const defaultBooklet=():Booklet=>({enabled:true,panels:2,autoPages:true,labels:true,badges:['HI-FI SOUND','STEREO','DOLBY ATMOS'],label:'',innerPaper:'#f6f2e8',innerInk:'#24211e',notes:''});
export function bookletPanelCount(p:Project){const b=p.booklet;if(!b?.enabled)return 1;const requested=Math.max(1,Math.min(4,Math.round(b.panels)||2));if(!b.autoPages)return requested;const chars=[...p.tracksA,...p.tracksB].reduce((n,t)=>n+t.title.length+trackNote(t,p).length+85,0)+(b.notes||'').length;const capacity=Math.max(180,Math.floor((INSERT_WIDTH-10)/1.25)*Math.floor((p.dimensions.h-20)/3.3));return Math.max(requested,Math.min(4,Math.ceil(chars/capacity)));}
export function trackNote(t:Track,_p:Project){return t.description?.trim()||'';}

export function sheetGeometry(p:Project,side:SheetSide='outer'):Geometry{if(side==='labelA'||side==='labelB'){const label=geometry({...p,format:'cassette',dimensions:{w:LABEL_WIDTH,h:LABEL_HEIGHT,d:0,flap:0,hole:0},insert:false});return {...label,cutouts:[{x:16.75,y:15,w:13,h:13,r:6.5},{x:59.25,y:15,w:13,h:13,r:6.5},{x:33,y:16,w:23,h:12,r:2}]};}const g=geometry(p);if(side==='inner'&&p.booklet?.enabled)return {...g,panels:g.panels.map(panel=>({...panel,x:g.w-panel.x-panel.w})),folds:g.folds.map(f=>({...f,x1:g.w-f.x1,x2:g.w-f.x2}))};return g;}
export function completeJcard(p:Project):Project{const isJcard=formats.find(f=>f.id===p.format)?.kind==='jcard';const base=isJcard?p:applyFormat(p,'jcard');const fitted=fitJcardLayout(base);return {...fitted,insert:true,booklet:{...defaultBooklet(),...base.booklet,enabled:true},showTrackNumbers:true,builtin:{},hideText:false,hideSpine:false,hideMeta:false,theme:'plain',smartDesign:undefined,titlePos:base.layers.some(l=>l.src&&l.panel==='background')?'hidden':'top',paper:'#151515',ink:'#faf6ec',accent:'#d6c6a6',catalog:base.catalog||'C60 / STEREO'};}

export function fitJcardLayout(p:Project):Project{const f=formats.find(f=>f.id===p.format)||formats[0];const dimensions={w:f.w,h:f.h,d:f.d,flap:f.flap||0,hole:0};const delta=dimensions.flap-p.dimensions.flap;const layers=p.layers.map(l=>l.x>=p.dimensions.flap?{...l,x:l.x+delta}:l);return {...p,dimensions,layers};}

export function albumArtwork(p:Project){const images=p.layers.filter(l=>l.visible&&l.type==='image'&&l.panel==='background'&&(!l.side||l.side==='outer'));return images.slice().reverse().find(l=>l.name==='Обложка из каталога')||images[images.length-1];}
export function replaceAlbumArtwork(p:Project,src?:string):Project{const front=geometry(p).panels.find(x=>x.id==='front')||geometry(p).panels[0];const layers=p.layers.filter(l=>!(l.type==='image'&&l.panel==='background'&&((l.name==='Обложка из каталога')||((!l.side||l.side==='outer')&&l.x===front.x&&l.y===front.y&&l.w===front.w&&l.h===front.h))));if(src)layers.push(layer({name:'Обложка из каталога',type:'image',src,x:front.x,y:front.y,w:front.w,h:front.h,panel:'background'}));const builtin={...p.builtin};for(const [id,override] of Object.entries(builtin)){if(override.src)delete builtin[id];}return {...p,smartDesign:undefined,layers,builtin,booklet:p.booklet?{...p.booklet,panorama:undefined}:undefined};}
export function cassetteBadges(p:Project){return [...new Set([p.booklet?.label,...(p.booklet?.badges||[])].filter((x):x is string=>!!x?.trim()).map(x=>x.trim()))].slice(0,3);}
