// Public catalogue metadata only: no credentials, paid APIs, or audio downloads.
export type CatalogQuery={q?:string;id?:string;kind?:string;source?:string};
export type JsonTransport=(url:string)=>Promise<any>;
export const catalogNames:Record<string,string>={deezer:'Deezer',musicbrainz:'MusicBrainz',itunes:'iTunes',tmdb:'TMDB'};
const duration=(ms:number)=>{const n=Math.max(0,Math.floor((Number(ms)||0)/1000));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;};
const numeric=(id:string)=>{if(!/^\d{1,20}$/.test(id))throw new Error('Некорректная ссылка на издание.');return id;};
const mbid=(id:string)=>{if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id))throw new Error('Некорректный идентификатор MusicBrainz.');return id;};
const artistCredit=(a:any[])=>Array.isArray(a)?a.map(x=>typeof x==='string'?x:(x.name||x.artist?.name||'')+(x.joinphrase||'')).join(''):'';
export function parseCatalogLink(text:string):CatalogQuery|null{if(!/^https?:\/\//i.test(text))return null;const u=new URL(text);if(u.protocol!=='https:')throw new Error('Используйте ссылку HTTPS.');if(['www.deezer.com','deezer.com'].includes(u.hostname)){const m=u.pathname.match(/\/(album|playlist|track)\/(\d+)(?:\/|$)/);if(!m)throw new Error('Вставьте полную ссылку Deezer на альбом, трек или плейлист.');return {id:m[2],kind:m[1]==='track'?'song':m[1],source:'deezer'};}if(['music.apple.com','itunes.apple.com'].includes(u.hostname)){if(u.pathname.includes('/playlist/'))throw new Error('Apple Music не предоставляет публичный треклист этого плейлиста. Найдите плейлист по названию во вкладке «Плейлисты» или вставьте список треков.');const id=u.searchParams.get('i')||u.pathname.match(/(?:id)?(\d+)\/?$/)?.[1];if(!id)throw new Error('Не удалось прочитать ссылку Apple Music. Используйте название альбома.');return {id,kind:'album',source:'itunes'};}if(u.hostname==='musicbrainz.org'){const m=u.pathname.match(/^\/release\/([a-f0-9-]+)\/?$/i);if(!m)throw new Error('Используйте ссылку MusicBrainz на конкретное издание /release/.');return {id:mbid(m[1]),kind:'album',source:'musicbrainz'};}if(u.hostname==='open.spotify.com')return {q:text,source:'spotify'};throw new Error('Поддерживаются ссылки Deezer, Apple Music и MusicBrainz. Плейлист Spotify можно найти по названию.');}
export async function deezerCatalog(params:CatalogQuery,get:JsonTransport){let {id,kind='album',q=''}=params;
 if(!id){const entity=kind==='playlist'?'playlist':kind==='song'?'track':'album';const d=await get(`https://api.deezer.com/search/${entity}?q=${encodeURIComponent(q)}&limit=24`);if(d.error)throw new Error('Deezer: '+(d.error.message||'каталог недоступен'));if(!Array.isArray(d.data))throw new Error('Deezer вернул неверный ответ.');return {results:d.data.map((x:any)=>({id:String(x.id),source:'deezer',kind,title:x.title,artist:x.artist?.name||x.user?.name||'Плейлист',image:x.cover_medium||x.picture_medium||x.album?.cover_medium||'',year:'',trackCount:x.nb_tracks||0})),sourceName:'Deezer'};}
 if(kind==='song'){const song=await get(`https://api.deezer.com/track/${numeric(id)}`);if(song.error||!song.album?.id)throw new Error('Трек Deezer не найден.');id=String(song.album.id);kind='album';}
 const entity=kind==='playlist'?'playlist':'album',d=await get(`https://api.deezer.com/${entity}/${numeric(id)}`);if(d.error||!d.id)throw new Error('Издание Deezer не найдено или недоступно.');const tracks:any[]=[];let index=0;
 // The public API pages tracklists. Never silently truncate the first page.
 while(true){const part=await get(`https://api.deezer.com/${entity}/${numeric(id)}/tracks?index=${index}&limit=100`);if(part.error||!Array.isArray(part.data))throw new Error('Не удалось загрузить полный список треков Deezer.');tracks.push(...part.data);if(!part.next||!part.data.length)break;index+=part.data.length;if(index>=2000)throw new Error('В плейлисте больше 2000 треков. Выберите меньшую подборку.');}
 return {title:d.title,artist:d.artist?.name||d.creator?.name||'',year:(d.release_date||d.creation_date||'').slice(0,4),description:d.description||'',image:d.cover_xl||d.picture_xl||d.cover_big||d.picture_big||'',link:d.link||`https://www.deezer.com/${entity}/${id}`,sourceName:'Deezer',label:d.label||'',credits:d.copyright||'',tracks:tracks.map(t=>({title:kind==='playlist'&&t.artist?.name?`${t.artist.name} — ${t.title}`:t.title,artist:t.artist?.name||'',duration:duration(t.duration*1000)}))};
}
export async function itunesCatalog(params:CatalogQuery,get:JsonTransport){const {kind='album',id,q=''}=params;if(!id){if(kind==='playlist')throw new Error('В iTunes нет публичного поиска плейлистов.');const entity=kind==='movie'?'movie':kind==='tv'?'tvSeason':kind==='song'?'song':'album';const d=await get(`https://itunes.apple.com/search?term=${encodeURIComponent(q)}&entity=${entity}&limit=24&country=US`);if(!Array.isArray(d.results))throw new Error('iTunes вернул неверный ответ.');return {results:d.results.map((x:any)=>({id:String(kind==='song'?x.trackId:(x.collectionId||x.trackId)),source:'itunes',title:x.collectionName||x.trackName,artist:x.artistName,year:(x.releaseDate||'').slice(0,4),image:x.artworkUrl100,kind})),sourceName:'iTunes'};}
 const music=!['movie','tv'].includes(kind);let d=await get(`https://itunes.apple.com/lookup?id=${numeric(id)}${music?'&entity=song&limit=200':''}&country=US`);let base=d.results?.[0];if(!base)throw new Error('Издание не найдено в iTunes.');if(base.kind==='song'&&base.collectionId){d=await get(`https://itunes.apple.com/lookup?id=${numeric(String(base.collectionId))}&entity=song&limit=200&country=US`);base=d.results?.[0]||base;}
 return {title:base.collectionName||base.trackName,artist:base.artistName||'',year:(base.releaseDate||'').slice(0,4),description:base.longDescription||base.shortDescription||'',runtime:!music&&base.trackTimeMillis?Math.round(base.trackTimeMillis/60000):'',rating:base.contentAdvisoryRating||'',image:base.artworkUrl100?.replace('100x100bb','1200x1200bb'),link:base.collectionViewUrl||base.trackViewUrl,sourceName:'iTunes',credits:base.copyright||'',tracks:(d.results||[]).filter((x:any)=>x.kind==='song').sort((a:any,b:any)=>(a.discNumber||1)-(b.discNumber||1)||(a.trackNumber||0)-(b.trackNumber||0)).map((x:any)=>({title:x.trackName,artist:x.artistName||'',duration:duration(x.trackTimeMillis)}))};
}
export async function musicbrainzCatalog(params:CatalogQuery,get:JsonTransport){const {id,q=''}=params;if(!id){const escaped=q.replace(/[+\-!(){}\[\]^"~*?:\\/]/g,' ');const d=await get(`https://musicbrainz.org/ws/2/release/?query=${encodeURIComponent(escaped)}&fmt=json&limit=24`);if(!Array.isArray(d.releases))throw new Error('MusicBrainz вернул неверный ответ.');return {results:d.releases.map((x:any)=>({id:x.id,source:'musicbrainz',kind:'album',title:x.title,artist:artistCredit(x['artist-credit']),year:(x.date||'').slice(0,4),image:'',country:x.country||''})),sourceName:'MusicBrainz'};}
 const d=await get(`https://musicbrainz.org/ws/2/release/${mbid(id)}?inc=recordings+artist-credits+labels&fmt=json`);if(!d.id)throw new Error('Издание не найдено в MusicBrainz.');const tracks=(d.media||[]).flatMap((m:any)=>(m.tracks||[]).map((t:any)=>({title:t.title||t.recording?.title||'',duration:duration(t.length||t.recording?.length||0)})));return {title:d.title,artist:artistCredit(d['artist-credit']),year:(d.date||'').slice(0,4),description:d.disambiguation||'',link:`https://musicbrainz.org/release/${id}`,sourceName:'MusicBrainz',label:(d['label-info']||[]).map((x:any)=>x.label?.name).filter(Boolean).join(' / '),tracks};
}
export async function freeCatalog(params:CatalogQuery,get:JsonTransport){const q=(params.q||'').trim();const linked=parseCatalogLink(q);if(linked&&linked.source!=='spotify')params={...params,...linked};if(linked?.source==='spotify')throw new Error('Для Spotify используйте название плейлиста. Бесплатный поиск плейлистов доступен через Deezer.');if(!params.id&&q.length<2)return {results:[],notice:'Введите не менее двух символов.'};const source=params.source||'auto',kind=params.kind||'album';const candidates=source==='auto'?(kind==='playlist'?['deezer']:['movie','tv'].includes(kind)?['itunes']:['deezer','itunes','musicbrainz']):[source];const problems:string[]=[];let empty:any=null;
 for(const source of candidates){try{const fn=source==='deezer'?deezerCatalog:source==='musicbrainz'?musicbrainzCatalog:source==='itunes'?itunesCatalog:null;if(!fn)throw new Error('Неизвестный источник каталога.');const result=await fn({...params,source},get);if(result.title||result.results?.length)return result;empty=result;}catch(e){problems.push(`${catalogNames[source]||source}: ${e instanceof Error?e.message:'не отвечает'}`);}}
 if(empty)return {...empty,notice:'Ничего не найдено. Попробуйте название исполнителя или другое название подборки.'};throw new Error('Источники поиска сейчас недоступны. Попробуйте другой источник или повторите позже. '+problems.join(' · '));}
