import {Project,Layer,Geometry,SheetSide,geometry,sheetGeometry,allLayers,albumArtwork} from './model';
const cache=new Map<string,Promise<HTMLImageElement>>();
export function loadImage(src:string):Promise<HTMLImageElement>{if(!cache.has(src)){cache.set(src,new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>{cache.delete(src);reject(new Error('Не удалось прочитать изображение'));};i.src=src;}));}return cache.get(src)!;}
export function fileData(file:Blob):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});}
const loadedFonts=new Set<string>();
export async function loadFonts(p:Project){await Promise.all(p.fonts.map(async f=>{if(!loadedFonts.has(f.name+f.src)){const ff=new FontFace(f.name,`url(${f.src})`);await ff.load();document.fonts.add(ff);loadedFonts.add(f.name+f.src);}}));}
function path(ctx:CanvasRenderingContext2D,g:Geometry){ctx.beginPath();if(g.disc){ctx.arc(g.w/2,g.h/2,Math.min(g.w,g.h)/2,0,2*Math.PI);if(g.hole)ctx.arc(g.w/2,g.h/2,g.hole/2,0,2*Math.PI,true);}else{g.outline.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();}}
function font(ctx:CanvasRenderingContext2D,size:number,bold:boolean,italic:boolean,family:string){ctx.font=`${italic?'italic ':''}${bold?'700':'400'} ${size}px "${family.replace(/["\\]/g,'')}", sans-serif`;}
type Run={text:string;color:string;size:number;font:string;bold:boolean;italic:boolean};
export function richRuns(l:Layer):Run[]{const base={color:l.color,size:l.size,font:l.font,bold:!!l.bold,italic:!!l.italic};let style={...base};const arr:Run[]=[];const tokens=(l.text||'').split(/(\*\*|(?<!\*)\*(?!\*)|\{#[0-9a-fA-F]{3,8}\}|\{\d+(?:\.\d+)?\}|\{\/s\}|\{\/f\}|\{\/\}|\{[^{}]+\})/g);for(const t of tokens){if(t==='**'){style.bold=!style.bold;continue;}if(t==='*'){style.italic=!style.italic;continue;}if(/^\{#/.test(t)){style.color=t.slice(1,-1);continue;}if(/^\{\d/.test(t)){style.size=Math.min(200,Math.max(1,Number(t.slice(1,-1))));continue;}if(t==='{\/}'){style.color=base.color;continue;}if(t==='{\/s}'){style.size=base.size;continue;}if(t==='{\/f}'){style.font=base.font;continue;}if(/^\{[^{}]+\}$/.test(t)){style.font=t.slice(1,-1);continue;}if(t)arr.push({...style,text:t});}return arr;}
export function textLayout(ctx:CanvasRenderingContext2D,l:Layer){const runs=richRuns(l);const make=(scale:number)=>{const lines:{runs:(Run&{w:number;ascent:number;descent:number})[];width:number;height:number}[]=[{runs:[],width:0,height:l.size*25.4/72*scale*1.2}];for(const run of runs){const parts=run.text.split(l.wrap===true?/(\n|[ \t]+)/:/(\n)/);for(let part of parts){if(!part)continue;if(part==='\n'){lines.push({runs:[],width:0,height:l.size*25.4/72*scale*1.2});continue;}const size=run.size*25.4/72*scale;font(ctx,size*10,run.bold,run.italic,run.font);const measure=(text:string)=>{const m=ctx.measureText(text);return {width:m.width/10,actualBoundingBoxAscent:m.actualBoundingBoxAscent/10,actualBoundingBoxDescent:m.actualBoundingBoxDescent/10};};let m=measure(part),line=lines[lines.length-1];if(l.wrap===true&&line.runs.length&&line.width+m.width>l.w){lines.push({runs:[],width:0,height:size*1.2});line=lines[lines.length-1];part=part.trimStart();m=measure(part);}if(l.minSize&&l.wrap!==true&&m.width>l.w){while(part.length>1&&measure(part+'…').width>l.w)part=part.slice(0,-1);part+='…';m=measure(part);}const ascent=m.actualBoundingBoxAscent||size*.8,descent=Math.max(0,m.actualBoundingBoxDescent||size*.2);line.runs.push({...run,text:part,size,w:m.width,ascent,descent});line.width+=m.width;line.height=Math.max(line.height,size*1.2);}}return lines;};let factor=1,lines=make(1);for(let i=0;i<8;i++){const height=lines.reduce((n,x)=>n+x.height,0),width=Math.max(0,...lines.map(x=>x.width)),ratio=Math.min(1,l.w/Math.max(width,.001),l.h/Math.max(height,.001));if(ratio>=.999)break;const next=factor*ratio*.995;factor=l.minSize?Math.max(l.minSize/l.size,next):next;lines=make(factor);}return {lines,factor,height:lines.reduce((n,x)=>n+x.height,0)};}
function drawText(ctx:CanvasRenderingContext2D,l:Layer){ctx.textBaseline='alphabetic';const layout=textLayout(ctx,l);ctx.save();ctx.scale(.1,.1);let y=l.vAlign==='middle'?(l.h-layout.height)/2:l.vAlign==='bottom'?l.h-layout.height:0;for(const line of layout.lines){let x=l.align==='center'?(l.w-line.width)/2:l.align==='right'?l.w-line.width:l.blockAlign==='center'?(l.w-Math.max(...layout.lines.map(x=>x.width)))/2:0;for(const r of line.runs){font(ctx,r.size*10,r.bold,r.italic,r.font);ctx.fillStyle=r.color;ctx.fillText(r.text,x*10,(y+(line.height-r.ascent-r.descent)/2+r.ascent)*10);x+=r.w;}y+=line.height;}ctx.restore();}
function drawBadge(ctx:CanvasRenderingContext2D,l:Layer){const pad=Math.min(.8,l.h*.16),icon=Math.min(l.h-pad*2,l.w*.18),x=pad,y=(l.h-icon)/2;ctx.save();ctx.strokeStyle=l.color;ctx.fillStyle=l.color;ctx.lineWidth=Math.max(.12,icon*.075);ctx.translate(x,y);if(l.badgeIcon==='hifi'){for(let i=0;i<5;i++){const h=icon*[.35,.65,1,.65,.35][i];ctx.beginPath();ctx.moveTo(icon*i/5,(icon-h)/2);ctx.lineTo(icon*i/5,(icon+h)/2);ctx.stroke();}}else if(l.badgeIcon==='stereo'){for(const cx of [icon*.28,icon*.72]){ctx.beginPath();ctx.arc(cx,icon/2,icon*.25,0,Math.PI*2);ctx.stroke();}}else if(l.badgeIcon==='music'){ctx.beginPath();ctx.moveTo(icon*.35,icon*.8);ctx.lineTo(icon*.35,icon*.15);ctx.lineTo(icon*.8,0);ctx.lineTo(icon*.8,icon*.65);ctx.stroke();for(const [cx,cy] of [[icon*.2,icon*.8],[icon*.65,icon*.65]]){ctx.beginPath();ctx.ellipse(cx,cy,icon*.16,icon*.12,-.3,0,Math.PI*2);ctx.fill();}}else{for(const flip of [false,true]){ctx.save();if(flip){ctx.translate(icon,0);ctx.scale(-1,1);}ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(icon*.2,0);ctx.bezierCurveTo(icon*.65,0,icon*.65,icon,icon*.2,icon);ctx.lineTo(0,icon);ctx.closePath();ctx.stroke();ctx.restore();}}ctx.restore();ctx.save();ctx.translate(icon+pad*2,0);drawText(ctx,{...l,w:Math.max(.2,l.w-icon-pad*3),vAlign:'middle',wrap:false});ctx.restore();}
export async function drawLayer(ctx:CanvasRenderingContext2D,l:Layer,images:Map<string,HTMLImageElement>){if(!l.visible)return;ctx.save();ctx.globalAlpha=l.opacity;ctx.globalCompositeOperation=l.blend||'source-over';ctx.translate(l.x+l.w/2,l.y+l.h/2);ctx.rotate(l.rotation*Math.PI/180);ctx.translate(-l.w/2,-l.h/2);if(l.bg){ctx.fillStyle=l.bg;ctx.fillRect(0,0,l.w,l.h);}ctx.beginPath();ctx.roundRect(0,0,l.w,l.h,Math.min(l.radius||0,l.w/2,l.h/2));ctx.clip();if(l.type==='text'){if(l.badgeIcon)drawBadge(ctx,l);else drawText(ctx,l);}else if(l.type==='rect'||l.type==='ellipse'){ctx.fillStyle=l.color;ctx.beginPath();if(l.type==='ellipse')ctx.ellipse(l.w/2,l.h/2,l.w/2,l.h/2,0,0,2*Math.PI);else ctx.roundRect(0,0,l.w,l.h,l.radius||0);ctx.fill();}else if(l.src){const img=images.get(l.src);if(img){ctx.filter=[l.blur?`blur(${l.blur}px)`:'',l.invert?'invert(1)':'',l.grayscale?'grayscale(1)':''].filter(Boolean).join(' ')||'none';ctx.translate(l.flipX?l.w:0,l.flipY?l.h:0);ctx.scale(l.flipX?-1:1,l.flipY?-1:1);const ratio=l.fit==='contain'?Math.min(l.w/img.width,l.h/img.height):Math.max(l.w/img.width,l.h/img.height);const z=l.zoom||1;const iw=(l.fit==='stretch'?l.w:img.width*ratio)*z,ih=(l.fit==='stretch'?l.h:img.height*ratio)*z;const x=(l.w-iw)/2+(l.cropX||0),y=(l.h-ih)/2+(l.cropY||0);if(l.tile){for(let tx=-iw;tx<l.w;tx+=iw)for(let ty=-ih;ty<l.h;ty+=ih)ctx.drawImage(img,tx+(l.cropX||0),ty+(l.cropY||0),iw,ih);}else ctx.drawImage(img,x,y,iw,ih);if(l.tint){ctx.globalCompositeOperation='source-atop';ctx.globalAlpha*=.5;ctx.fillStyle=l.tint;ctx.fillRect(0,0,l.w,l.h);}}}ctx.restore();if(l.border){ctx.save();ctx.translate(l.x+l.w/2,l.y+l.h/2);ctx.rotate(l.rotation*Math.PI/180);ctx.strokeStyle=l.borderColor||l.color;ctx.lineWidth=l.border;ctx.strokeRect(-l.w/2,-l.h/2,l.w,l.h);ctx.restore();}}
const coverColors=new Map<string,string>();
async function coverColor(p:Project){const src=albumArtwork(p)?.src;if(!src)return p.accent;if(coverColors.has(src))return coverColors.get(src)!;try{const img=await loadImage(src),sample=document.createElement('canvas');sample.width=sample.height=32;const ctx=sample.getContext('2d')!;ctx.drawImage(img,0,0,32,32);const pixels=ctx.getImageData(0,0,32,32).data,bins=new Map<string,{count:number;r:number;g:number;b:number}>();for(let i=0;i<pixels.length;i+=4){if(pixels[i+3]<128)continue;const [r,g,b]=[pixels[i],pixels[i+1],pixels[i+2]],key=[r,g,b].map(v=>v>>4).join(',');const bin=bins.get(key)||{count:0,r:0,g:0,b:0};bin.count++;bin.r+=r;bin.g+=g;bin.b+=b;bins.set(key,bin);}const best=[...bins.values()].sort((a,b)=>b.count-a.count)[0];const color=best?'#'+[best.r,best.g,best.b].map(v=>Math.round(v/best.count).toString(16).padStart(2,'0')).join(''):p.accent;if(coverColors.size>20)coverColors.clear();coverColors.set(src,color);return color;}catch{return p.accent;}}
export async function render(p:Project,canvas:HTMLCanvasElement,options:{dpi?:number;guides?:boolean;blank?:boolean;selection?:string;grid?:boolean;side?:SheetSide}={}){const side=options.side||'outer',g=sheetGeometry(p,side),scale=(options.dpi||160)/25.4;if(Math.ceil(g.w*scale)*Math.ceil(g.h*scale)>65000000)throw new Error('Для этого размера выберите меньшее разрешение экспорта.');canvas.width=Math.ceil(g.w*scale);canvas.height=Math.ceil(g.h*scale);const ctx=canvas.getContext('2d')!;ctx.scale(scale,scale);const color=options.blank?p.accent:await coverColor(p);const layers=allLayers(p,side).map(l=>/^(inner-)?spine\d*-title$/.test(l.id)?{...l,color}:l);const images=new Map<string,HTMLImageElement>();if(!options.blank){await loadFonts(p);await Promise.all(layers.filter(x=>x.visible&&x.src).map(async x=>images.set(x.src!,await loadImage(x.src!))));}ctx.save();path(ctx,g);ctx.clip('evenodd');if(!options.blank){ctx.fillStyle=p.paper;ctx.fillRect(0,0,g.w,g.h);for(const panel of g.panels){if(side==='outer'&&p.panelColors[panel.id]){ctx.fillStyle=p.panelColors[panel.id];ctx.fillRect(panel.x,panel.y,panel.w,panel.h);}if(panel.id==='glue'){ctx.save();ctx.globalAlpha=.15;ctx.strokeStyle=p.ink;ctx.lineWidth=.3;for(let y=panel.y-panel.w;y<panel.y+panel.h;y+=3){ctx.beginPath();ctx.moveTo(panel.x,y);ctx.lineTo(panel.x+panel.w,y+panel.w);ctx.stroke();}ctx.restore();}}
 const front=g.panels.find(x=>x.id==='front');if(side==='outer'&&front&&p.theme!=='plain'){ctx.save();ctx.beginPath();ctx.rect(front.x,front.y,front.w,front.h);ctx.clip();if(p.theme==='signal'){ctx.fillStyle=p.accent;ctx.fillRect(front.x,front.y,front.w,front.h*.56);ctx.fillStyle=p.ink;ctx.font=`900 ${front.w*.65}px Arial`;ctx.textBaseline='top';ctx.fillText('90',front.x-2,front.y+front.h*.04,front.w+3);ctx.lineWidth=.4;for(let x=front.x;x<front.x+front.w;x+=3){ctx.beginPath();ctx.moveTo(x,front.y+front.h*.5);ctx.lineTo(x+front.w*.3,front.y+front.h*.62);ctx.strokeStyle=p.paper;ctx.stroke();}}
 else if(p.theme==='waves'){const gradient=ctx.createLinearGradient(front.x,front.y,front.x+front.w,front.y+front.h);gradient.addColorStop(0,p.accent);gradient.addColorStop(1,p.paper);ctx.fillStyle=gradient;ctx.fillRect(front.x,front.y,front.w,front.h*.62);ctx.globalAlpha=.2;ctx.strokeStyle=p.ink;ctx.lineWidth=.5;for(let n=0;n<28;n++){ctx.beginPath();for(let x=0;x<front.w;x+=.5){const y=front.y+front.h*.22+Math.sin(x/front.w*7+n*.13)*front.h*.12+n*.8;x?ctx.lineTo(front.x+x,y):ctx.moveTo(front.x+x,y);}ctx.stroke();}}
 else if(p.theme==='mono'){ctx.fillStyle=p.ink;ctx.fillRect(front.x,front.y,front.w,front.h*.57);ctx.fillStyle=p.paper;ctx.font=`900 ${front.w*.28}px Arial`;ctx.fillText('SIDE A',front.x+5,front.y+front.h*.29);}
 else if(p.theme==='grid'){ctx.strokeStyle=p.accent;ctx.lineWidth=.8;for(let x=front.x;x<front.x+front.w;x+=8){ctx.beginPath();ctx.moveTo(x,front.y);ctx.lineTo(x,front.y+front.h);ctx.stroke();}for(let y=front.y;y<front.y+front.h;y+=8){ctx.beginPath();ctx.moveTo(front.x,y);ctx.lineTo(front.x+front.w,y);ctx.stroke();}}
 else {const colors:Record<string,string[]>= {'blockbuster':['#164895','#ffda39'],'movie-gallery':['#b62128','#ffffff'],'hollywood-video':['#43244f','#ffd344'],'video-ezy':['#e45925','#ffffdc']};const c=colors[p.theme]||[p.ink,p.accent];ctx.fillStyle=c[0];ctx.fillRect(front.x,front.y,front.w,front.h*.25);ctx.fillStyle=c[1];ctx.font=`bold ${front.w*.12}px Arial`;ctx.fillText('VIDEO CLUB',front.x+4,front.y+front.h*.15);ctx.fillStyle=c[0];ctx.fillRect(front.x,front.y+front.h-4,front.w,4);}ctx.restore();}
 for(const l of layers.filter(l=>l.panel==='background'))await drawLayer(ctx,l,images);
 if(side==='outer'&&front&&p.overlay!=='none'){ctx.save();let gr:CanvasGradient;if(p.overlay==='vignette'){gr=ctx.createRadialGradient(front.x+front.w/2,front.y+front.h/2,0,front.x+front.w/2,front.y+front.h/2,Math.max(front.w,front.h)*.65);gr.addColorStop(0,'transparent');gr.addColorStop(1,p.overlayColor);}else{const reverse=p.overlay==='top';gr=ctx.createLinearGradient(0,front.y,0,front.y+front.h);gr.addColorStop(0,reverse?p.overlayColor:'transparent');gr.addColorStop(1,reverse?'transparent':p.overlayColor);}ctx.globalAlpha=p.overlayOpacity/100;ctx.fillStyle=gr;ctx.fillRect(front.x,front.y,front.w,front.h);ctx.restore();}
 for(const l of layers.filter(l=>l.panel!=='background'))await drawLayer(ctx,l,images);
 if(p.wear>0){ctx.save();ctx.globalAlpha=p.wear/600;ctx.fillStyle='#ffffff';let seed=1988;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<2500;i++)ctx.fillRect(rnd()*g.w,rnd()*g.h,rnd()*.35+.1,rnd()*1.4+.1);ctx.strokeStyle='#fff';ctx.lineWidth=.8;g.folds.forEach(f=>{ctx.beginPath();ctx.moveTo(f.x1,f.y1);ctx.lineTo(f.x2,f.y2);ctx.stroke();});ctx.restore();}}
 ctx.restore();if(g.cutouts?.length){ctx.save();ctx.globalCompositeOperation='destination-out';for(const c of g.cutouts){ctx.beginPath();ctx.roundRect(c.x,c.y,c.w,c.h,c.r);ctx.fill();}ctx.restore();}if(p.notch&&p.format.includes('slipcover')){const front=g.panels.find(x=>x.id==='front');if(front){ctx.save();ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(front.x+front.w/2,front.y,7,0,Math.PI);ctx.fill();ctx.restore();}}
 if(options.grid){ctx.strokeStyle='#d67c923d';ctx.lineWidth=.15;for(let x=0;x<g.w;x+=5){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,g.h);ctx.stroke();}for(let y=0;y<g.h;y+=5){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(g.w,y);ctx.stroke();}}
 if(options.guides||options.blank){if(p.cuts||options.blank){ctx.strokeStyle=options.blank?'#333333':'#343a3977';ctx.lineWidth=.2;path(ctx,g);ctx.stroke();for(const c of g.cutouts||[]){ctx.beginPath();ctx.roundRect(c.x,c.y,c.w,c.h,c.r);ctx.stroke();}}if(p.folds||options.blank){ctx.strokeStyle=options.blank?'#b05273':'#935065bb';ctx.lineWidth=.2;ctx.setLineDash([1.2,1]);g.folds.forEach(f=>{ctx.beginPath();ctx.moveTo(f.x1,f.y1);ctx.lineTo(f.x2,f.y2);ctx.stroke();});ctx.setLineDash([]);}}
 if(options.selection){const l=layers.find(l=>l.id===options.selection);if(l){ctx.save();ctx.translate(l.x+l.w/2,l.y+l.h/2);ctx.rotate(l.rotation*Math.PI/180);ctx.strokeStyle='#ac7800';ctx.fillStyle='#fff';ctx.lineWidth=.35;ctx.strokeRect(-l.w/2,-l.h/2,l.w,l.h);const r=1.3;for(const [x,y] of [[-l.w/2,-l.h/2],[l.w/2,-l.h/2],[l.w/2,l.h/2],[-l.w/2,l.h/2]]){ctx.fillRect(x-r,y-r,r*2,r*2);ctx.strokeRect(x-r,y-r,r*2,r*2);}ctx.beginPath();ctx.moveTo(0,-l.h/2);ctx.lineTo(0,-l.h/2-6);ctx.stroke();ctx.beginPath();ctx.arc(0,-l.h/2-6,1.5,0,2*Math.PI);ctx.fill();ctx.stroke();ctx.restore();}}return g;}
export function localPoint(x:number,y:number,l:Layer){const dx=x-l.x-l.w/2,dy=y-l.y-l.h/2,a=-l.rotation*Math.PI/180;return {x:dx*Math.cos(a)-dy*Math.sin(a)+l.w/2,y:dx*Math.sin(a)+dy*Math.cos(a)+l.h/2};}
export function hitLayer(p:Project,x:number,y:number,side:SheetSide='outer'){return allLayers(p,side).reverse().find(l=>{if(!l.visible||l.locked)return false;const q=localPoint(x,y,l);return q.x>=0&&q.x<=l.w&&q.y>=0&&q.y<=l.h;});}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
export const paperSizes:Record<string,[number,number]>={A4:[210,297],A3:[297,420],Letter:[215.9,279.4],Tabloid:[279.4,431.8],'13×19':[330.2,482.6],A2:[420,594],A1:[594,841]};
export function pageLayout(g:Geometry,paper:string,copies:number,margin:number,bleed:number){let [pw,ph]=paper==='custom'?[g.w+2*(margin+bleed),copies*(g.h+2*bleed)+(copies-1)*5+2*margin]:paperSizes[paper]||paperSizes.A4;const w=g.w+2*bleed,h=g.h+2*bleed;let cells:{x:number;y:number}[]=[];for(const landscape of [false,true]){const W=landscape?ph:pw,H=landscape?pw:ph;const cols=Math.floor((W-2*margin+5)/(w+5)),rows=Math.floor((H-2*margin+5)/(h+5));if(cols*rows>=copies){const ncols=Math.min(cols,copies),nrows=Math.ceil(copies/ncols),startX=(W-(ncols*w+(ncols-1)*5))/2,startY=(H-(nrows*h+(nrows-1)*5))/2;for(let i=0;i<copies;i++)cells.push({x:startX+(i%ncols)*(w+5)+bleed,y:startY+Math.floor(i/ncols)*(h+5)+bleed});return {w:W,h:H,cells};}}throw new Error(`Макет ${g.w.toFixed(1)} × ${g.h.toFixed(1)} мм (${copies} экз.) не помещается на ${paper}. Выберите больший лист или «По макету». Масштаб не изменён.`);}
export type PrintSettings={dpi:number;paper:string;copies:number;margin:number;bleed:number;marks:boolean;side?:SheetSide};
export function exportSides(p:Project):SheetSide[]{return p.booklet?.enabled&&p.insert?['outer','inner',...(p.booklet.labels?['labelA','labelB'] as SheetSide[]:[])]:['outer'];}
export async function renderSheets(p:Project,settings:PrintSettings,blank=false){const sides=blank?['outer'] as SheetSide[]:exportSides(p);const sheets:{side:SheetSide;canvas:HTMLCanvasElement;g:Geometry}[]=[];for(const side of sides){const canvas=document.createElement('canvas');const g=await render(p,canvas,{dpi:settings.dpi,guides:true,blank,side});sheets.push({side,canvas,g});}return sheets;}
export async function exportProject(p:Project,type:'png'|'pdf'|'blank'|'clipboard',settings:PrintSettings){const title=(p.name||'tape-studio').replace(/[^\p{L}\p{N} _.-]/gu,'').slice(0,80);
 if(type==='clipboard'){const canvas=document.createElement('canvas');await render(p,canvas,{dpi:settings.dpi,guides:true,side:settings.side});const blob=await new Promise<Blob>(res=>canvas.toBlob(b=>res(b!),'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);return;}
 const sheets=await renderSheets(p,settings,type==='blank');
 if(type==='png'){for(const sheet of sheets){const blob=await new Promise<Blob>(res=>sheet.canvas.toBlob(b=>res(b!),'image/png'));download(blob,title+(sheets.length>1?'-'+sheet.side:'')+'.png');}return;}
 const {jsPDF}=await import('jspdf');const main=sheets[0].g,page=pageLayout(main,settings.paper,settings.copies,settings.margin,settings.bleed);const pdf=new jsPDF({unit:'mm',format:[page.w,page.h],orientation:page.w>page.h?'landscape':'portrait',compress:true});pdf.setProperties({title:p.name,creator:'Tape Studio'});
 const marks=(x:number,y:number,w:number,h:number)=>{if(!settings.marks)return;pdf.setDrawColor('#222222');pdf.setLineWidth(.15);for(const xx of [x,x+w])for(const yy of [y,y+h]){const dx=xx===x?-1:1,dy=yy===y?-1:1;pdf.line(xx+dx,yy,xx+dx*4,yy);pdf.line(xx,yy+dy,xx,yy+dy*4);}};
 for(let n=0;n<sheets.length;n++){const sheet=sheets[n];if(sheet.side==='labelB')continue;
 const label=sheet.side==='labelA';const current=label?pageLayout(sheet.g,settings.paper,settings.copies*2,settings.margin,settings.bleed):page;
 if(n)pdf.addPage([current.w,current.h],current.w>current.h?'landscape':'portrait');
 for(let i=0;i<current.cells.length;i++){const pos=current.cells[i],x=sheet.side==='inner'?current.w-pos.x-sheet.g.w:pos.x,y=pos.y;const image=label?sheets.find(s=>s.side===(i%2?'labelB':'labelA'))!:sheet;
 if(settings.bleed&&type!=='blank'){pdf.setFillColor(sheet.side==='inner'?p.booklet?.innerPaper||p.paper:p.paper);pdf.rect(x-settings.bleed,y-settings.bleed,sheet.g.w+2*settings.bleed,sheet.g.h+2*settings.bleed,'F');}pdf.addImage(image.canvas.toDataURL('image/png'),'PNG',x,y,sheet.g.w,sheet.g.h);marks(x,y,sheet.g.w,sheet.g.h);}}
 download(pdf.output('blob'),title+(type==='blank'?'-template':'')+'.pdf');}
